try:
    # -- Distribution mode --
    # import from _version.py generated by setuptools_scm during release
    from ._version import version as __version__
except ImportError:
    # -- Source mode --
    try:
        # use setuptools_scm to get the current version from src using git
        from pathlib import Path as _Path

        from setuptools_scm import get_version as _gv

        __version__ = _gv(_Path(__file__).parent.parent)
    except ImportError:
        # setuptools_scm is not available, use a default version
        __version__ = "0.0.0+unknown"


# useful constants
from math import (
    e,
    inf,
    nan,
    pi,
)

from . import lazy
from .autoray import (
    DoFunc,
    astype,
    backend_like,
    compose,
    conj,
    dag,
    do,
    get_backend,
    get_common_dtype,
    get_dtype_name,
    get_lib_fn,
    get_namespace,
    imag,
    infer_backend,
    infer_backend_multi,
    is_array,
    is_scalar,
    ndim,
    numpy,
    real,
    register_backend,
    register_function,
    reshape,
    set_backend,
    shape,
    size,
    to_backend_dtype,
    to_numpy,
    transpose,
    tree_apply,
    tree_flatten,
    tree_iter,
    tree_map,
    tree_unflatten,
)
from .compiler import autojit
from .grad import stop_gradient

__all__ = (
    "astype",
    "autojit",
    "backend_like",
    "compose",
    "conj",
    "dag",
    "do",
    "DoFunc",
    "e",
    "get_backend",
    "get_common_dtype",
    "get_dtype_name",
    "get_lib_fn",
    "get_namespace",
    "imag",
    "inf",
    "infer_backend_multi",
    "infer_backend",
    "is_array",
    "is_scalar",
    "lazy",
    "nan",
    "ndim",
    "numpy",
    "pi",
    "real",
    "register_backend",
    "register_function",
    "reshape",
    "set_backend",
    "shape",
    "size",
    "stop_gradient",
    "to_backend_dtype",
    "to_numpy",
    "transpose",
    "tree_apply",
    "tree_flatten",
    "tree_iter",
    "tree_map",
    "tree_unflatten",
)
