from . import linalg
from .core import (
    Function,
    LazyArray,
    Variable,
    add,
    allclose,
    angle,
    arccos,
    arccosh,
    arcsin,
    arcsinh,
    arctan,
    arctanh,
    argmax,
    argmin,
    argsort,
    array,
    ascend,
    broadcast_to,
    clip,
    compute,
    concatenate,
    conj,
    cos,
    cosh,
    count_nonzero,
    cumsum,
    descend,
    diag,
    diagonal,
    einsum,
    empty,
    equal,
    exp,
    expand_dims,
    eye,
    flip,
    floordivide,
    get_source,
    identity,
    imag,
    kron,
    log,
    log2,
    log10,
    matmul,
    mean,
    moveaxis,
    multiply,
    ones,
    permute_dims,
    prod,
    real,
    reshape,
    shared_intermediates,
    sign,
    sin,
    sinh,
    sort,
    split,
    sqrt,
    stack,
    std,
    swapaxes,
    take,
    take_along_axis,
    tan,
    tanh,
    tensordot,
    trace,
    transpose,
    truedivide,
    var,
    where,
    zeros,
)
from .core import abs_ as abs
from .core import all_ as all
from .core import any_ as any
from .core import complex_ as complex
from .core import max_ as max
from .core import min_ as min
from .core import sum_ as sum

__all__ = (
    "Function",
    "LazyArray",
    "Variable",
    "abs",
    "add",
    "all",
    "allclose",
    "angle",
    "any",
    "arccos",
    "arccosh",
    "arcsin",
    "arcsinh",
    "arctan",
    "arctanh",
    "argmax",
    "argmin",
    "argsort",
    "array",
    "ascend",
    "broadcast_to",
    "clip",
    "complex",
    "compute",
    "concatenate",
    "conj",
    "cos",
    "cosh",
    "count_nonzero",
    "cumsum",
    "descend",
    "diag",
    "diagonal",
    "einsum",
    "empty",
    "equal",
    "exp",
    "expand_dims",
    "eye",
    "flip",
    "floordivide",
    "get_source",
    "identity",
    "imag",
    "kron",
    "linalg",
    "log",
    "log2",
    "log10",
    "matmul",
    "max",
    "mean",
    "min",
    "moveaxis",
    "multiply",
    "ones",
    "permute_dims",
    "prod",
    "real",
    "reshape",
    "shared_intermediates",
    "sign",
    "sin",
    "sinh",
    "sort",
    "split",
    "sqrt",
    "stack",
    "std",
    "sum",
    "swapaxes",
    "take",
    "take_along_axis",
    "tan",
    "tanh",
    "tensordot",
    "trace",
    "transpose",
    "truedivide",
    "var",
    "where",
    "zeros",
)


try:
    from opt_einsum.backends.dispatch import _aliases

    _aliases["autoray"] = "autoray.lazy"
except ImportError:  # pragma: no cover
    pass
